version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - arigato
  - bgrotate
  - gsap
  - iconify
  - koko
  - kono
  - naitokosuke
  - Noto
  - onryou
  - owakariitadaketadaroka
  - ponyo
  - rgba
  - saurce
  - slidev
  - tokatsu
  - Tsunagi
  - unok
ignoreWords: []
import: []
