version: "0.2"
words:
  - Alolu
  - antfu
  - Bazze
  - colada
  - Colada
  - École
  - esbuild
  - ESGI
  - Génie
  - Hatena
  - Informatique
  - Loadershnq
  - Morote
  - MVVM
  - Naito
  - naitokosuke
  - nuxi
  - Nuxt
  - nuxtjs
  - pinia
  - posva
  - seriph
  - signup
  - slidev
  - swrv
  - textlintrc
  - unplugin
  - victorgarciaesgi
  - vite
  - vuejs
  - zenn
